CREATE TABLE employees (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(100) NOT NULL,
    email  VARCHAR(255) NOT NULL,
    active BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE devices (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_tag VARCHAR(50)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    category      VARCHAR(50)  NOT NULL,
    status        VARCHAR(20)  NOT NULL,
    CONSTRAINT uq_devices_inventory_tag UNIQUE (inventory_tag),
    CONSTRAINT ck_devices_status CHECK (status IN ('AVAILABLE', 'MAINTENANCE', 'RETIRED'))
);

CREATE TABLE loans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id   BIGINT      NOT NULL REFERENCES devices (id),
    employee_id BIGINT      NOT NULL REFERENCES employees (id),
    borrowed_at TIMESTAMPTZ NOT NULL,
    due_at      TIMESTAMPTZ NOT NULL,
    returned_at TIMESTAMPTZ,
    extended    BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE TABLE waitlist_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id   BIGINT      NOT NULL REFERENCES devices (id),
    employee_id BIGINT      NOT NULL REFERENCES employees (id),
    created_at  TIMESTAMPTZ NOT NULL
);
